### ISSUE TITLE
New colours for SSHWS

### ISSUE THREAD

**Issue by Bustycat** [titoxd/wptc-track#10]
The [colours for SSHWS](https://en.wikipedia.org/wiki/Template:Storm_colour) on English Wikipedia are now different.

- #8D75E6 for Category 5 (#A188FC is incorrect)
- #FF738A for Category 4
- #FF9E59 for Category 3
- #FFD98C for Category 2
- #FFFFD9 for Category 1
- #4DFFFF for Storm
- #6EC1EA for Depression
- #C0C0C0 for Unknown

We should think about how we implement.

**Comment by Jasper-A-D** [comment]
My PR #11 addresses this @Bustycat. Since the program exists primarily to serve Wikipedia I have changed the scale definitions; those who wish to use legacy colors will have to use color arguments to override.

**Comment by titoxd** [comment]
Merged to the main branch in 86800105d70e9fdfa209e56d820d487ea4f29503
